Models/task.cs
using CompanyWebApp.Data.enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CompanyWebApp.Models
{
    [Serializable]
    public class task
    {
        [Key]
        [Required]public int Id { get; set; }
        [Required(ErrorMessage = " Write task description")] public string taskDesc { get; set; }
        public TskStatus taskStatues { get; set; }

        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }


        //relationship with comments
        public List<comment>? Comments { get; set; }
        
        //relationship between task and its emp
        [Required] public int Employee_Id { get; set; }
        [ForeignKey("Employee_Id")]
        public Employee? employee { get; set; }


    }
}

Controllers/CommentsController.cs
using CompanyWebApp.Data;
using CompanyWebApp.Data.Services;
using CompanyWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CompanyWebApp.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ICommentService _service;
        private readonly IHttpContextAccessor contextAccessor;
        public CommentsController(ICommentService service, IHttpContextAccessor contextAccessor)
        {
            _service = service;
            this.contextAccessor = contextAccessor;
        }
        public IActionResult AddComment()
        {
            comment newComment = new comment();
            return View(newComment);
        }
        [HttpPost]
        public IActionResult AddComment(comment newComment)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("ViewTask", "Tasks", newComment.Task_Id);
            }

            _service.Add(newComment);
            return RedirectToAction("ViewTask", "Tasks", new { taskId = newComment.Task_Id });
        }
    }
}

Controllers/DepartmentsController.cs
using CompanyWebApp.Data;
using CompanyWebApp.Data.Services;
using CompanyWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;

namespace CompanyWebApp.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly IDepartmentService _service;
        public DepartmentsController(IDepartmentService service)
        {
            _service = service; 
        }
        public IActionResult Display()
        {
            var data = _service.getAllDepartments();
            return View(data);
        }
        public IActionResult AddDep()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddDep(department dep)
        {
            if(! ModelState.IsValid)
            return View(dep);
            _service.Add(dep);
            return RedirectToAction(nameof(Display));
        }
        public IActionResult EditDep(int depId)
        {
            var data = _service.getDepByID(depId);
            if (data == null) return View("Not Found");
            return View(data);
        }
        [HttpPost]
        public IActionResult EditDep(department dep)
        {
            if (!ModelState.IsValid)
            {
                return View(dep);
            }
            _service.Update(dep);
            return RedirectToAction(nameof(Display));
        }
        public IActionResult DelDep(int DepId)
        {
            var data = _service.getDepByID(DepId);
            if (data == null) return View("Not Found");
            return View(data);
        }
        [HttpPost, ActionName("DeleteDep")]
        public IActionResult DelEmpConfirmed(int DepId)
        {
            try
            {
                // Check if the department ID is associated with any employee
                var hasEmployees = _service.HasEmployees(DepId);
                if (hasEmployees)
                {
                    return View("Error", "You cannot delete this department because it has associated employees.");
                }
                var data = _service.getDepByID(DepId);
                if (data == null)
                {
                    return View("NotFound");
                }
                else
                {
                    _service.Delete(DepId);
                    return RedirectToAction(nameof(Display));
                }
            }
            catch (Exception ex)
            {
                return View("Error", ex.Message);
            }
        }


    }
}

Controllers/EmployeesController.cs
using CompanyWebApp.Data;
using CompanyWebApp.Data.Services;
using CompanyWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace CompanyWebApp.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly IEmployeesService _service;
        private readonly IHttpContextAccessor contextAccessor;
        public EmployeesController(IEmployeesService service, IHttpContextAccessor contextAccessor)
        {
            _service = service;
            this.contextAccessor = contextAccessor;
        }
        public IActionResult Display()
        {
            var data = _service.getAllEmployees();
            return View(data);
        }
        public IActionResult AddEmp()
        {
            Employee newEmployee = new Employee();
            return View(newEmployee);
        }
        [HttpPost]
        public IActionResult AddEmp(Employee newEmployee)
        {
            if (!ModelState.IsValid)
            {
                return View(newEmployee);
            }

            _service.Add(newEmployee);
            return RedirectToAction(nameof(Display));
        }

        public IActionResult EditEmp(int EmpId)
        {
            var data = _service.getEmployeeById(EmpId);
            if (data == null) return View("Not Found");
            return View(data);
        }
        [HttpPost]
        public IActionResult EditEmp(Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return View( employee);
            }
            _service.Update(employee);
            return RedirectToAction(nameof(Display));
        }
        public IActionResult DelEmp(int EmpId)
        {
            var data = _service.getEmployeeById(EmpId);
            if (data == null) return View("Not Found");
            return View(data);
        }
        [HttpPost, ActionName("DeleteEmp")]
        public IActionResult DelEmpConfirmed(int EmpId)
        {
            var data = _service.getEmployeeById(EmpId);
            if (data == null) return View("Not Found");
            data.empStatus = Data.enums.EmpStatus.Inactive;
            _service.Update(data);
            return RedirectToAction(nameof(Display));
        }
        public IActionResult DisplayContact()
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            var sup = _service.getAllSuperv(emp.Id);
            return View(sup);
        }
    }
}

Controllers/TasksController.cs
using CompanyWebApp.Data;
using CompanyWebApp.Data.Services;
using CompanyWebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Threading.Tasks;
using System.Security.Claims;

namespace CompanyWebApp.Controllers
{
    public class TasksController : Controller
    {
        private readonly ITaskService _taskService;
        private readonly IHttpContextAccessor contextAccessor;
        public TasksController(ITaskService taskService, IHttpContextAccessor contextAccessor)
        {
            _taskService = taskService;
            this.contextAccessor = contextAccessor;
        }
        public IActionResult Display()
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            var data = _taskService.selectMangerOrSuper(emp.Id);
            return View(data);
        }
        public IActionResult DisplayForEmp()
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            List<task> data = _taskService.getAllTasksforEmp(emp.Id);
            var allEmpTasks = new object[] { emp, data };
            return View(allEmpTasks);
        }
        public IActionResult EmpCal()
        {
            Employee emp = new Employee();
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            return View(emp);
        }

        public IActionResult ViewTask(int taskId) 
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            task taskData = _taskService.View(taskId);
            var allComments = _taskService.getAllcommentsFortask(taskId);
            comment com = new comment();
            var updatedInfo = new object[] { emp, taskData , allComments , com};
            return View(updatedInfo);
        }
        public IActionResult EditTask(int taskId)
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            task taskData = _taskService.View(taskId);
            var updatedInfo = new object[] { emp, taskData};
            return View(updatedInfo);
        }
        [HttpPost]
        public IActionResult EditTask(task updatesTask)
        {
            if (!ModelState.IsValid)
            {
                return View(updatesTask);
            }
            _taskService.Update(updatesTask);
            return RedirectToAction("DisplayForEmp");
        }
        [HttpPost]
        public IActionResult DelTask(int taskId)
        {
            task taskData = _taskService.View(taskId);
            taskData.taskStatues = Data.enums.TskStatus.Cancelled;
            _taskService.Update(taskData);
            return RedirectToAction("DisplayForEmp" , "Tasks");
        }

        public IActionResult AddTask()
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            task newTask = new task();
            var updatedInfo = new object[] { emp, newTask };
            return View(updatedInfo);
        }
        [HttpPost]
        public IActionResult AddTask(task newTask)
        {
            if (!ModelState.IsValid)
            {
                return View(newTask);
            }
            _taskService.Add(newTask);
            return RedirectToAction("DisplayForEmp");
        }

        //Manager tasks controlling 
        public IActionResult MngAssignTask()
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            List<Employee> empList = _taskService.getDepEmps(emp.Dep_Id);
            task newTask = new task();
            var updatedInfo = new object[] { empList, newTask };
            return View(updatedInfo);
        }
        [HttpPost]
        public IActionResult MngAssignTask(task newTask)
        {
            if (!ModelState.IsValid)
            {
                return View(newTask);
            }

            _taskService.Add(newTask);
            return RedirectToAction("Display");
        }

        public IActionResult MngEditTask(int taskId)
        {
            string employeeJson = contextAccessor.HttpContext.Session.GetString("LoggedEmployee");
            Employee emp = JsonConvert.DeserializeObject<Employee>(employeeJson);
            List<Employee> empList = _taskService.getDepEmps(emp.Dep_Id);
            task taskData = _taskService.View(taskId);
            var updatedInfo = new object[] { empList, taskData };
            return View(updatedInfo);
        }
        [HttpPost]
        public IActionResult MngEditTask(task updatesTask)
        {
            if (!ModelState.IsValid)
            {
                return View(updatesTask);
            }
           // task taskData = _taskService.View(taskId);
            _taskService.Update(updatesTask);
            return RedirectToAction("Display");
        }
        public IActionResult MngDelTask(int taskId)
        {
            task taskData = _taskService.View(taskId);
            taskData.taskStatues = Data.enums.TskStatus.Cancelled;
            _taskService.Update(taskData);
            return RedirectToAction("Display", "Tasks");
        }
    }
}

Views/Tasks/AddTask.cshtml
@model object[]
@using CompanyWebApp.Data.enums;
@{
    ViewData["Title"] = "Task Details";
    var employee = Model[0] as Employee;
    var data = Model[1] as task;
    data.Employee_Id = employee.Id;
    data.StartDate = DateTime.Today;
    data.EndDate = DateTime.Today;
}
<style>
    a.btn.my-btn:hover {
        background: #e60000;
    }
</style>

@if (employee.empRole == EmpRole.Admin)
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Display">Employees</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Display">Departments</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>
                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}
else if (employee.empRole == EmpRole.Manager || employee.empRole == EmpRole.Supervisor)
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Display">My Team's Tasks</a>
                        </li>
                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}
else
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DisplayContact">Contact Supervisors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>

                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h2>Add Task</h2>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <form asp-action="AddTask">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <input asp-for="@(((task)data).Employee_Id)" class="form-control" type="hidden" />
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).taskDesc)" class="control-label">Task Description</label>
                        <input asp-for="@(((task)data).taskDesc)" class="form-control" />
                        <span asp-validation-for="@(((task)data).taskDesc)" class="text-danger"></span>
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).taskStatues)" class="control-label">Status</label>
                        <select asp-for="@(((task)data).taskStatues)" class="form-control">
                            @foreach (var stt in Enum.GetValues(typeof(TskStatus)))
                            {
                                <option value="@stt">@stt</option>
                            }
                        </select>
                        <span asp-validation-for="@(((task)data).taskStatues)" class="text-danger"></span>
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).StartDate)" class="control-label">Task Start Date</label>
                        <input asp-for="@(((task)data).StartDate)" class="form-control" />
                        <span asp-validation-for="@(((task)data).StartDate)" class="text-danger"></span>
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).EndDate)" class="control-label">End Date</label>
                        <input asp-for="@(((task)data).EndDate)" class="form-control" />
                        <span asp-validation-for="@(((task)data).EndDate)" class="text-danger"></span>
                        <br />
                        <br />
                    </div>
                    <div class="form-group text-center">
                        <input type="submit" value="Add" class="btn btn-outline-dark" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


Views/Tasks/ViewTask.cshtml
@model object[]
@using CompanyWebApp.Data.enums;
@{
    ViewData["Title"] = "Task Details";
    var employee = Model[0] as Employee;
    var data = Model[1] as task;
    var com = Model[3] as comment;
    com.Emp_Id = employee.Id;
    com.Task_Id = data.Id;
}
<style>
    a.btn.my-btn:hover {
        background: #e60000;
    }
</style>

@if (employee.empRole == EmpRole.Admin)
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Display">Employees</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Display">Departments</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>
                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}
else if (employee.empRole == EmpRole.Manager || employee.empRole == EmpRole.Supervisor)
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="Display">My Team's Tasks</a>
                        </li>
                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}
else
{
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand">PGESCo Tasks Calender</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="EmpCal"><i class="badge-info bi-house "> </i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="DisplayContact">Contact Supervisors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tasks" asp-action="DisplayForEmp">My Tasks</a>
                        </li>

                    </ul>
                    <a class="btn my-btn btn-dark" asp-area="" asp-controller="Home" asp-action="LogIn">Logout</a>
                </div>
            </div>
        </nav>
    </header>
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h2>Task details</h2>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">

                <form asp-action="ViewTask">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <label asp-for="@(((task)data).taskDesc)" class="control-label">Task Description</label>
                        <input asp-for="@(((task)data).taskDesc)" class="form-control" readonly />
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).taskStatues)" class="control-label">Task Status</label>
                        <input asp-for="@(((task)data).taskStatues)" class="form-control" readonly />
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).StartDate)" class="control-label">Task Start Date</label>
                        <input asp-for="@(((task)data).StartDate)" class="form-control" readonly />
                        <br />
                    </div>
                    <div class="form-group">
                        <label asp-for="@(((task)data).EndDate)" class="control-label">End Date</label>
                        <input asp-for="@(((task)data).EndDate)" class="form-control" readonly />
                        <br />
                        <br />
                    </div>
                </form>


            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table table-auto">
            <thead>
                <tr>
                    <th> <b>Comments</b></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in (List<comment>)Model[2])
                {
                    <tr>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.employee.Name)</td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.Text)</td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form method="post" asp-controller="Comments" asp-action="AddComment">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group">
                        <input asp-for="@(((comment)com).Task_Id)" class="form-control" readonly type="hidden" />
                        <input asp-for="@(((comment)com).Emp_Id)" class="form-control" readonly type="hidden" />
                        <br />
                    </div>

                    <div class="form-group">
                        <input asp-for="@(((comment)com).Text)" class=" form-control" />
                        <span asp-validation-for="@(((comment)com).Text)" class="text-danger"></span>
                        <br />
                    </div>
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-outline-dark"><i class="bi bi-pencil-square "></i>  Add Comment</button>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
